# Shortcuts of the terminal

# OS window shortcuts
map ctrl+q close_os_window

# Tab shortcuts
map ctrl+t new_tab
map ctrl+shift+t launch --type=tab vim
map ctrl+w close_tab
map ctrl+i set_tab_title
map ctrl+e next_tab

# Window shortcut
map ctrl+f new_window
map ctrl+g close_window
map ctrl+j next_window
map ctrl+k previous_window

# Miscellaneous
map ctrl+l clear_terminal to_cursor active
