# Style of the windows and tabs

# Font styles, size and ligatures
font_family       JetBrainsMono Nerd Font Regular
bold_font         JetBrainsMono Nerd Font Bold
italic_font       JetBrainsMono Nerd Font Italic
bold_italic_font  JetBrainsMono Nerd Font Bold Italic
font_size         18
disable_ligatures never

# Window style
hide_window_decorations titlebar-only
window_padding_width    10 20

# Tab bar style
tab_bar_min_tabs            1
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted

# Layouts
enabled_layouts tall
